### ISSUE TITLE
WordPress 5.8.0 not tagged yet

### ISSUE THREAD

**Issue by thefrosty** [wp-phpunit/issues#11]
Is there a way to escalate getting the new version built and tagged?

**Comment by aaemnnosttv** [comment]
Thanks for raising this. Looks like this is due to the build running on travis-ci.org which is no longer running builds. I'm working on getting it migrated to travis-ci.com so it should be up and running again soon 🙂

**Comment by aaemnnosttv** [comment]
Done! 🙂 
https://github.com/wp-phpunit/wp-phpunit/releases/tag/5.8.0
https://packagist.org/packages/wp-phpunit/wp-phpunit#5.8.0
