### ISSUE TITLE
Timeline on Changes to the WordPress Core PHP Test Suite

### ISSUE THREAD

**Issue by thefrosty** [wp-phpunit/issues#12]
This just dropped, and wondering on the timeline.

https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/

**Comment by aaemnnosttv** [comment]
Hey there, thanks for asking.

The new requirement for `yoast/phpunit-polyfills` is coming in [5.9](https://make.wordpress.org/core/5-9/), currently in trunk.

If you're asking if `wp-phpunit` will be updated to include this as a dependency, I've thought about it and decided not to include it. This package is a subset of the WordPress core develop repo, and that's it. It technically depends on WordPress and PHPUnit as well but doesn't declare these as dependencies via Composer either. I'll update the docs to reflect this but you should only need to require the added package as a dev dependency.

**Comment by benjaminpick** [comment]
Polyfills are needed for 5.8.2 now ...

**Comment by benjaminpick** [comment]
Can you update the example-plugin as well, please?

**Comment by aaemnnosttv** [comment]
Updated 👍
