### ISSUE TITLE
Causes VSCode intelephense to "crash"

### ISSUE THREAD

**Issue by oxyc** [wp-phpunit/issues#13]
Currently using WP_UnitTestCase anywhere causes VSCode intelephense to entirely stop working but seemingly without any erros in its log output...

I guess this is not directly related to these repos but wondering if something can be done here to fix it?

**Comment by aaemnnosttv** [comment]
That's odd! If anything, it sounds like a problem with the extension. Sorry to not be of much help here, but I don't see how it could be caused by this package.

**Comment by johnbillion** [comment]
I've been using this library for a long while without seeing an issue with Intelephense. Probably worth trying to isolate exactly where the issue is and then reporting it to the Intelephense author.
