### ISSUE TITLE
WordPress 5.2

### ISSUE THREAD

**Issue by remcotolsma** [wp-phpunit/issues#4]
Is @wp-phpunit-bot down? No release for WordPress 5.2:

- https://github.com/WordPress/wordpress-develop/releases/tag/5.2.0
- https://github.com/WordPress/wordpress-develop/releases/tag/5.2.1

**Comment by aaemnnosttv** [comment]
Hey, thanks for bringing this to my attention. The build is failing since 5.2.

I'll get this fixed asap.

**Comment by aaemnnosttv** [comment]
All good now 👍 https://github.com/wp-phpunit/wp-phpunit/releases

**Comment by andrewmclagan** [comment]
Thanks!
